const dosen = [
  {
    nama: "Dr. Hermawan Syahputra, M.Si.",
    imgUrl: "Hermawan.jpg",
    ttl: "Jati Mulyo, 30-09-1980",
    golonganJabatan: "III/c/Lektor",
    bidangKeahlian: "Image Processing, Pattern Recognition, Computer Vision",
    pendidikan: [
      "S1 Matematika USU",
      "S2 Ilmu Komputer IPB",
      "S3 Ilmu Komputer UGM",
    ],
  },
  {
    nama: "Said Iskandar, S.Si., M.Si",
    imgUrl: "said_iskandar.jpg",
    ttl: "Rantau, 18 Maret 1977",
    golonganJabatan: "III/c / Lektor",
    bidangKeahlian: "Computational Science",
    pendidikan: ["S1 Matematika USU", "S2 Sains Komputasi"],
  },
  {
    nama: "Zulfahmi Indra, S.Si., M.Cs.",
    imgUrl: "Zulfahmi_Indra.jpeg",
    ttl: "Medan, 11 Februari 1973",
    golonganJabatan: "III/c 	/ Lektor",
    bidangKeahlian: "Artificial Intellegent (Algoritma Genetika)",
    pendidikan: ["S1 Matematika USU", "S2 Ilmu Komputer UGM"],
  },
  {
    nama: "Dr. Arnita, M.Si.",
    imgUrl: "arnita.jpg",
    ttl: "Pangkalan Brandan, Langkat, 21 Juni 1976",
    golonganJabatan: "III/d /Lektor",
    bidangKeahlian: "Statistic and Data Mining",
    pendidikan: ["S1 Matematika USU", "S2 Statistika IPB", "S3 Matematika USU"],
  },
  {
    nama: "Yulita Molliq Rangkuti, S.Si., M.Sc., Ph.D.",
    imgUrl: "yulita.jpg",
    ttl: "Lubuk Pakam, 22 Januari 1976",
    golonganJabatan: "III/d / Lektor Kepala",
    bidangKeahlian: "Mathematic Modelling",
    pendidikan: [
      "S1 Matematika USU",
      "S2 Matematika Universiti Kebangsaan Malaysia",
      "S3 Matematika Universiti Kebangsaan Malaysia",
    ],
  },
  {
    nama: "Nice Rejoice Refisis S.Si., M.Si.",
    imgUrl: "nica.png",
    ttl: "Medan, 03 Maret 1984",
    golonganJabatan: "III/b / Asisten Ahli",
    bidangKeahlian: "Mathematics",
    pendidikan: ["S1 Matematika Unimed", "S2 Matematika USU"],
  },
  {
    nama: "Kana Saputra S, S.Pd., M.Kom.",
    imgUrl: "kana_s.jpg",
    ttl: "Sigli, 16 Agustus 1990",
    golonganJabatan: "III/b Asisten Ahli",
    bidangKeahlian: "Bioinformatic and Data Mining",
    pendidikan: ["S1 Pendidikan Matematika UNSYIAH", "S2 Ilmu Komputer IPB"],
  },
  {
    nama: "Insan Taufik, M.Kom.",
    imgUrl: "insan_taufik.jpg",
    ttl: "Aceh Tenggara, 09 Februari 1991",
    golonganJabatan: "III/b Lektor",
    bidangKeahlian: "Web Programming, Image Processing",
    pendidikan: ["S1 Ilmu Komputer", "S2 Imu Komputer UPI"],
  },
  {
    nama: "Debi Yandra Niska, M.Kom",
    imgUrl: "deby.jpg",
    ttl: "Pesisir Selatan, 19 November 1990",
    golonganJabatan: "III/b / Asisten Ahli",
    bidangKeahlian: "Decision Support System",
    pendidikan: ["S1 Ilmu Komputer UPI", "S2 Ilmu Komputer UPI"],
  },
  {
    nama: "Prof. Dr. Makmur Sirait, M.Si.",
    imgUrl: "makmur.png",
    ttl: "Lumbanjulu/Taput 06-03-1963",
    golonganJabatan: "IV/d / Profesor",
    bidangKeahlian: "Fisika Komputasi",
    pendidikan: [
      "S1 Pend FIsika IKIP Medan",
      "S2 UGM Instrumentasi",
      "S3 USU Material",
    ],
  },
  {
    nama: "Prof. Dr. Nurdin Bukit, M.Si.",
    imgUrl: "nurdin.png",
    ttl: "Suka Maju, 18 April 1964",
    golonganJabatan: "IV/d / Profesor",
    bidangKeahlian: "Fisika Komputasi",
    pendidikan: ["S1 USU Fisika", "S2 ITB Material", "S3 USU Kimia Fisika"],
  },
  {
    nama: "Dr. Mulyono, M.Si",
    imgUrl: "mulyono.png",
    ttl: "P. Kacang, 31 Desember 1971",
    golonganJabatan: "IV/a / Lektor Kepala",
    bidangKeahlian: "Pemodelan dan Graf",
    pendidikan: ["S1 Matematika USU", "S2 Matematika UGM", "S3 Matematika USU"],
  },
  {
    nama: "Dr. Elmanani Simamora, M.Si.",
    imgUrl: "elmanani.png",
    ttl: "Kampung Solok, 16 November 1972",
    golonganJabatan: "III/c Lektor",
    bidangKeahlian: "Statistika",
    pendidikan: ["S1 Matematika USU", "S2 Matematika ITB", "S3 Matematika UGM"],
  },
  {
    nama: "Dr. Faiz Ahyaningsih, M.Si.",
    imgUrl: "faiz.png",
    ttl: "Sukoharjo, 26 Juni 1966",
    golonganJabatan: "IV/a Lektor Kepala",
    bidangKeahlian: "Matematika Optimasi",
    pendidikan: ["S1 Matematika UGM", "S2 Matematika USU", "S3 Matematika USU"],
  },
];

export default dosen;
